docs(zh): update zh docs from en and format some en docs
vuejs/router pull request #1350
Opened 2022-03-20 15:10 UTC by KimYangOfCat

Hi，when I start learning router V4, I found the chinese docs lag behind the English docs. So I update the chinese docs based the commit f672bf01902368e65ca33e247b53d537ef0edc6c .

2022-04-02 06:12 UTC, KimYangOfCat commented
@Jinjiang Hi, jinjiang, can you help me to review this PR ? Thanks~

2022-04-11 14:12 UTC, edison1105 commented on docs/zh/guide/advanced/composition-api.md
> +`route` 对象是一个响应式对象，所以它的任何属性都可以被监听，但你应该**避免监听整个 `route`** 对象。在大多数情况下，你应该直接观测你期望改变的参数。
我觉得这里可以将观测可以改为监听

2022-04-11 14:13 UTC, edison1105 commented on docs/zh/guide/advanced/extending-router-link.md
> +    // `props`包含`to`和任何其他可以传递给<router-link>的 prop
```suggestion
    // `props`包含`to`和任何其他可以传递给 <router-link> 的 prop
```

2022-04-11 14:15 UTC, edison1105 commented on docs/zh/guide/advanced/navigation-guards.md
> +      // 确保用户未认证
如果改成 `检查用户是否登录` 是否更贴切？

2022-04-11 14:18 UTC, edison1105 commented on docs/zh/guide/essentials/navigation.md
> +当指定 `params `时，确保提供 `string `或 `number`（或者对于[可重复的参数](./route-matching-syntax.md#repeatable-params)数组）。**任何其他类型（如 `undefined`、`false`等）将被自动字符串化**。对于[可选参数](./route-matching-syntax.md#repeatable-params)
这里有点不通顺啊

2022-04-11 14:20 UTC, edison1105 commented on docs/zh/guide/essentials/route-matching-syntax.md
> +默认情况下，所有路由是不区分大小写的，并且匹配带有或不带有尾部斜线的路由。例如，路由`/users`匹配`/users`、`/users/`，甚至`/Users/`。这种行为可以通过`strict`和`sensitive`选项来配置，它们可以在路由器和路由级别上设置：
路由器？🤔
中英文之间我们建议增加一个空格，例如：路由 `/users` 匹配 `/users`

2022-04-11 14:22 UTC, edison1105 requested changes
中英文之间我们建议增加一个空格，例如：路由 /users 匹配 /users
辛苦。🙏🏻

2022-04-12 00:52 UTC, edison1105 commented on docs/zh/api/index.md
> +  严格检查路径末尾是否有尾部斜线（`/`）。默认为`false`，意味着默认情况下，路由`/users`同时匹配`/users`和`/users/`。注意这也可以在路由级别上设置。
```suggestion
  严格检查路径末尾是否有尾部斜线（`/`）。默认为 `false`，意味着默认情况下，路由 `/users` 同时匹配 `/users` 和 `/users/`。注意这也可以在路由级别上设置。
```

2022-04-12 00:53 UTC, edison1105 commented on docs/zh/api/index.md
> +  路由被添加时的子路由记录。如果没有则为空数组。注意这个数组在`addRoute()`和`removeRoute()`被调用时不会更新。
```suggestion
  路由被添加时的子路由记录。如果没有则为空数组。注意这个数组在 `addRoute()` 和 `removeRoute()` 被调用时不会更新。
```

2022-04-12 00:56 UTC, edison1105 commented on docs/zh/guide/advanced/transitions.md
> +Vue可能会自动复用看起来相似的组件，从而忽略了任何过渡。幸运的是，可以[添加一个 `key` 属性](https://v3.vuejs.org/api/special-attributes.html#key)来强制过渡。这也允许你在相同路由上用不同的参数触发过渡：
```suggestion
Vue 可能会自动复用看起来相似的组件，从而忽略了任何过渡。幸运的是，可以[添加一个 `key` 属性](https://v3.vuejs.org/api/special-attributes.html#key)来强制过渡。这也允许你在相同路由上使用不同的参数触发过渡：
```

2022-04-12 10:20 UTC, KimYangOfCat commented
@edison1105  多谢你的 review，后续我再检查一下中英文格式以及常见的名词错误，短时间的初步翻译，可能会有很多纰漏，请见谅

2022-04-12 12:23 UTC, KimYangOfCat commented on docs/zh/guide/advanced/navigation-guards.md
> +      // 确保用户未认证
是的，稍后我直接修改吧

2022-04-13 01:07 UTC, KimYangOfCat commented on docs/zh/guide/essentials/route-matching-syntax.md
> +默认情况下，所有路由是不区分大小写的，并且匹配带有或不带有尾部斜线的路由。例如，路由`/users`匹配`/users`、`/users/`，甚至`/Users/`。这种行为可以通过`strict`和`sensitive`选项来配置，它们可以在路由器和路由级别上设置：
已添加，“路由器”，这个的翻译错误了，这里的 router 和 route，我重新理解后应该指全局路由和当前路由。

2022-04-13 01:09 UTC, KimYangOfCat commented on docs/zh/guide/essentials/navigation.md
> +当指定 `params `时，确保提供 `string `或 `number`（或者对于[可重复的参数](./route-matching-syntax.md#repeatable-params)数组）。**任何其他类型（如 `undefined`、`false`等）将被自动字符串化**。对于[可选参数](./route-matching-syntax.md#repeatable-params)
> 当指定 `params` 时，可提供 `string` 或 `number` 参数（或者对于[可重复的参数](./route-matching-syntax.md#repeatable-params)可提供一个数组）。**任何其他类型（如 `undefined`、`false` 等）都将被自动字符串化**。对于[可选参数](./route-matching-syntax.md#repeatable-params)，你可以提供一个空字符串（`""`）来跳过它。

这里重新翻译了一下，应该通顺了很多

2022-05-12 09:34 UTC, posva commented
@KimYangOfCat @edison1105 I was planning on moving vue router repo to a monorepo which would complicate this PR. Is it okay if we merge this as it is to move forward and then review it again?

2022-05-12 11:05 UTC, edison1105 commented
@posva I thinks its readly to merge now. @KimYangOfCat

2022-05-13 01:00 UTC, KimYangOfCat commented
yes, it's ok to merge now

2022-05-13 08:54 UTC, merged