fix: warn against named parent routes
vuejs/router pull request #1385
Opened 2022-04-29 14:51 UTC by Eating-Eating

(fix #1376[,#1376])
A route with a name and a child with an empty path without a name should warn when adding the route (inside of the matcher)

2022-05-02 15:32 UTC, posva requested changes
Thanks! Can you also make sure this work with multiple levels of nested routes with empty paths?

2022-05-02 15:32 UTC, posva commented on src/matcher/index.ts
> +      checkChildMissingNameWithEmptyPath(mainNormalizedRecord, parent)
```suggestion
    if (__DEV__) {
      checkChildMissingNameWithEmptyPath(mainNormalizedRecord, parent)
    }
```

2022-05-04 17:58 UTC, Eating-Eating commented on __tests__/matcher/addingRemoving.spec.ts
> +    it('warn if child route missing a required name', () => {
Thanks for your reply, should I add another test case or just change this case into a multiple levels of nested routes?

2022-05-04 18:00 UTC, Eating-Eating commented
> Thanks! Can you also make sure this work with multiple levels of nested routes with empty paths?

Thanks for your reply, should I add another test case or just change this case into a multiple levels of nested routes?

2022-05-04 22:08 UTC, posva commented
Adding a new test case and ensuring the implementation works 🙂

2022-05-12 09:20 UTC, posva commented on src/matcher/index.ts
> +      `A child route with an empth path that has a named parent route needs a name`
```suggestion
      `The route named "${parent.record.name}" has a child without a name and an empty path. Using that name won't render the empty path child so you probably want to move the name to the child instead. If this is intentional, add a name to the child route to remove the warning.
```

2022-05-12 09:20 UTC, posva commented on __tests__/matcher/addingRemoving.spec.ts
> +      expect('route needs a name').toHaveBeenWarned()
```suggestion
      expect('has a child without a name').toHaveBeenWarned()
```

2022-05-12 09:20 UTC, posva commented on __tests__/matcher/addingRemoving.spec.ts
> +      expect('route needs a name').not.toHaveBeenWarned()
```suggestion
      expect('has a child without a name').not.toHaveBeenWarned()
```

2022-05-12 09:20 UTC, posva commented on __tests__/matcher/addingRemoving.spec.ts
> +      expect('route needs a name').toHaveBeenWarned()
```suggestion
      expect('has a child without a name').toHaveBeenWarned()
```

2022-05-12 09:20 UTC, posva commented on __tests__/matcher/addingRemoving.spec.ts
> +      expect('route needs a name').not.toHaveBeenWarned()
```suggestion
      expect('has a child without a name').not.toHaveBeenWarned()
```

2022-05-12 09:32 UTC, posva commented
Thanks, I did some refactor on my end but didn't have push rights: https://github.com/vuejs/router/pull/1396

2022-05-12 09:32 UTC, closed without merging