docs: add Vue Mastery links for Vue Router Cheat Sheet
vuejs/router pull request #1571
Opened 2022-10-08 00:06 UTC by tutorialcode

2022-10-12 04:00 UTC, tutorialcode commented on packages/docs/.vitepress/components/VueMasteryHomeLink.vue
> +          <img alt="Vue Mastery Logo" width="25px" src="https://storage.googleapis.com/vue-mastery.appspot.com/flamelink/media/vue-mastery-logo.png">
Yeah, it's updated with a smaller image (50px)

2022-10-12 15:00 UTC, tutorialcode commented
@posva I updated the image link with a smaller version (50px)

2022-10-22 17:24 UTC, posva requested changes

2022-10-22 17:24 UTC, posva commented on packages/docs/.vitepress/components/VueMasteryLogoLink.vue
> +  for: string,
let's just use a boolean
```suggestion
  description?: boolean,
```

2022-10-22 17:24 UTC, posva commented on packages/docs/.vitepress/components/VueMasteryLogoLink.vue
> +    <span v-if="forVueRouterCheatSheet" class="description">
that way, this becomes 
```suggestion
    <span v-if="description" class="description">
```

2022-10-22 17:24 UTC, posva commented on packages/docs/.vitepress/components/VueMasteryLogoLink.vue
> +  <a :href="link" target="_blank">
Let's put the href directly here

2022-10-22 17:24 UTC, posva commented on packages/docs/.vitepress/components/VueMasteryLogoLink.vue
> +const forVueRouterCheatSheet = props.for === 'vue-router-cheat-sheet'
let's remove all of this and just put the href

2022-10-26 02:43 UTC, tutorialcode commented
I refactored the code (putting the link in href directly)

2022-10-26 12:29 UTC, posva approved these changes

2022-10-26 12:29 UTC, merged