docs(zh): typed routes translate
vuejs/router pull request #1752
Opened 2023-03-24 13:32 UTC by Lmmmmmm-bb

2023-04-03 07:58 UTC, posva requested changes
Thanks!

2023-04-04 02:26 UTC, Jinjiang commented on packages/docs/zh/guide/advanced/typed-routes.md
> +[查看插件](https://github.com/posva/unplugin-vue-router) 的 GitHub 仓库获取安装说明和文档。
这两句话之间建议不折行，因为会导致两句话之间多渲染一个空格。

2023-04-04 02:26 UTC, Jinjiang commented on packages/docs/zh/guide/advanced/typed-routes.md
> +# Typed Routes (v4.1.0+)
```suggestion
# 类型化路由 (v4.1.0+)
```

@Justineo 对于 Typed Routes 的翻译有什么建议？(下同)

2023-04-04 02:26 UTC, Jinjiang commented on packages/docs/zh/guide/advanced/typed-routes.md
> +从 v4.1.0 开始，我们引入一个新的功能，称为 Typed Routes。这个**实验性**功能通过 Vite/webpack/Rollup 插件启用。
```suggestion
从 v4.1.0 开始，我们引入一个新的功能，称为类型化路由。这个**实验性**功能通过 Vite/webpack/Rollup 插件启用。
```

2023-04-05 01:47 UTC, Jinjiang commented on packages/docs/zh/guide/advanced/typed-routes.md
> +# Typed Routes (v4.1.0+)
和 @Justineo 讨论后达成一致译为“类型化路由”

2023-04-05 01:50 UTC, Jinjiang approved these changes

2023-04-05 01:50 UTC, merged