docs(zh): translate some API pages
vuejs/router pull request #1774
Opened 2023-04-04 03:20 UTC by Jinjiang

@Justineo I translated some API pages. We need to align whether it's a good pattern to go before dealing with the rest part. Thanks.

2023-04-07 15:24 UTC, Justineo requested changes

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/NavigationFailure.md
> +该导航由来的路由路径
感觉有点不太符合中文表达，是不是可以考虑说：“上一个路由位置”或者直接“来自哪一个路由位置”？

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +其 RegExp 是否应该在末尾加一个 `$` 以匹配到结束。
```suggestion
其 RegExp 是否应该在末尾加一个 `$` 以匹配到末尾。
```

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +路由器使用的历史记录模式。大多数应用应该使用 `createWebHistory`，但这需要正确配置服务器。你也可以使用 `createWebHashHistory` 来实现基于*哈希*的历史记录，无需配置服务器，但这种方式不会被搜索引擎处理，SEO 的效果较差。
这个咱们要尽量对齐行么？

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +路由器使用的历史记录模式。大多数应用应该使用 `createWebHistory`，但这需要正确配置服务器。你也可以使用 `createWebHashHistory` 来实现基于*哈希*的历史记录，无需配置服务器，但这种方式不会被搜索引擎处理，SEO 的效果较差。
```suggestion
路由器使用的历史记录模式。大多数应用应该使用 `createWebHistory`，但这需要正确配置服务器。你也可以使用 `createWebHashHistory` 来实现基于 *hash* 的历史记录，无需配置服务器。但这种方式不会被搜索引擎处理，SEO 的效果较差。
```

这个 hash 不应该翻译成哈希，就是指 `#` 符号开头的片段，感觉可以不用翻译。

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +活跃的 [RouterLink](../index.md#routerlink) 的默认 CSS class。如果没有提供，则会使用 `router-link-active`。
活跃同上

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +精确活跃的 [RouterLink](../index.md#routerlink) 的默认 CSS class。如果没有提供，则会使用 `router-link-exact-active`。
同上

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +假设你想使用这个 [qs 包](https://github.com/ljharb/qs) 来解析查询，那么你可以同时提供 `parseQuery` 和 `stringifyQuery`：
```suggestion
假设你想使用 [qs 包](https://github.com/ljharb/qs) 来解析查询，那么你可以同时提供 `parseQuery` 和 `stringifyQuery`：
```

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +  // `to` 和 `from` 都是路由路径
我会觉得路径的原文是 path，倾向于区分一下，你觉得呢

2023-04-07 15:24 UTC, Justineo commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +是否不允许有尾部斜线。
```suggestion
是否禁止尾部斜线。
```

2023-04-09 02:09 UTC, Jinjiang commented on packages/docs/zh/api/interfaces/NavigationFailure.md
> +该导航由来的路由路径
有道理

2023-04-09 02:09 UTC, Jinjiang commented on packages/docs/zh/api/interfaces/NavigationFailure.md
> +该导航由来的路由路径
```suggestion
上一个路由位置
```

2023-04-09 02:09 UTC, Jinjiang commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +路由器使用的历史记录模式。大多数应用应该使用 `createWebHistory`，但这需要正确配置服务器。你也可以使用 `createWebHashHistory` 来实现基于*哈希*的历史记录，无需配置服务器，但这种方式不会被搜索引擎处理，SEO 的效果较差。
我理解中文没法完全对齐行，不然汉字之间会有空格。我暂时没有什么特别好的办法。

2023-04-09 02:09 UTC, Jinjiang commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +活跃的 [RouterLink](../index.md#routerlink) 的默认 CSS class。如果没有提供，则会使用 `router-link-active`。
```suggestion
匹配当前路由的 [RouterLink](../index.md#routerlink) 默认的 CSS class。如果没有提供，则会使用 `router-link-active`。
```

2023-04-09 02:09 UTC, Jinjiang commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +精确活跃的 [RouterLink](../index.md#routerlink) 的默认 CSS class。如果没有提供，则会使用 `router-link-exact-active`。
```suggestion
严格匹配当前路由的 [RouterLink](../index.md#routerlink) 默认的 CSS class。如果没有提供，则会使用 `router-link-exact-active`。
```

2023-04-09 02:09 UTC, Jinjiang commented on packages/docs/zh/api/interfaces/RouterOptions.md
> +  // `to` 和 `from` 都是路由路径
路由地址？

2023-04-09 03:26 UTC, Justineo approved these changes

2023-04-09 03:28 UTC, merged