docs(zh): translate the warning part of passing_props to Chinese
vuejs/router pull request #2161
Opened 2024-03-05 05:15 UTC by make17better

### Finished the translation of Passing Props to Route Components

Before: 
![图片](https://github.com/vuejs/router/assets/45524718/87b6f783-22da-4714-982c-2c01e630d458)

After: 
![图片](https://github.com/vuejs/router/assets/45524718/c9958d23-36c0-46ee-b193-e17df15cfc3a)

2024-03-05 15:35 UTC, Jinjiang requested changes

2024-03-05 15:35 UTC, Jinjiang commented on packages/docs/zh/guide/essentials/passing-props.md
> +在这种情况下，**所有视图组件**都会接收到 `view-prop`。通常这并不是一个好的做法，因为这意味着所有的视图组件都声明了一个不一定正确的 `view-prop` 属性。请尽可能使用上述的其他选项。
```suggestion
在这种情况下，**所有视图组件**都会接收到 `view-prop`。通常这并不是一个好主意，因为这意味着所有的视图组件都声明了一个 `view-prop` prop，但这未必需要。所以请尽可能使用上述的其他选项。
```

2024-03-05 15:35 UTC, Jinjiang commented on packages/docs/zh/guide/essentials/passing-props.md
> +@@ -94,6 +94,6 @@ You can also pass any props via the [`<RouterView>` slot](../advanced/router-vie
这行应该是误操作了，请恢复到原文

2024-03-06 03:24 UTC, make17better commented on packages/docs/zh/guide/essentials/passing-props.md
> +@@ -94,6 +94,6 @@ You can also pass any props via the [`<RouterView>` slot](../advanced/router-vie
抱歉，确实误操作了，已恢复原文。

2024-03-06 23:49 UTC, Jinjiang approved these changes

2024-03-06 23:49 UTC, merged