docs: fix typo
vuejs/router pull request #2173
Opened 2024-03-08 15:24 UTC by make17better

### Fix typo

**Description:** A period is missing between `instances` and `Having`, click [here](https://router.vuejs.org/zh/api/interfaces/RouteRecordNormalized.html#Properties-instances) for details.

**Snapshot:**
![图片](https://github.com/vuejs/router/assets/45524718/251836b0-1a34-4d26-85e2-88f20e2f6e46)

2024-03-08 15:43 UTC, make17better commented
I've already added a period, but why it still doesn't work in the [Deploy Preview](https://router.vuejs.org/api/interfaces/RouteRecordNormalized.html#instances)? Is this caused by the VitePress configuration or the Markdown syntax of VitePress?

2024-03-08 16:53 UTC, posva requested changes
Can you fix it in the source code please? This is generated

2024-03-08 18:17 UTC, make17better commented
> Can you fix it in the source code please? This is generated

OK, I got it, I will fix it.

2024-03-09 00:57 UTC, make17better commented
> Can you fix it in the source code please? This is generated

Actually, I've changed it in the source code before I open this PR. Seems to be a Netlify deployment issue? Because everything worked fine in the dist got after I executed `pnpm run docs:build` locally. Finally, I executed `pnpm run docs:preview`, it also works.

I'm sorry I can't fix this problem because I can't (or I just don't know how to) debug in a cloud service environment like the Netlify Deploy. Please feel free to enlighten me.

Here's the screenshot of my local preview: 
![图片](https://github.com/vuejs/router/assets/45524718/7d0d6616-d98b-4bd4-8e50-87b1218208c4)

2024-03-09 08:05 UTC, posva commented
I see, thank you. In that case it will appear in the next deployment

2024-03-09 08:05 UTC, closed without merging