docs(zh): sync to d842b6f
vuejs/router pull request #2244
Opened 2024-05-21 17:49 UTC by Jinjiang

Update the Chinese docs

2024-05-26 09:27 UTC, posva commented
Feel free to merge when you think it's ready @Jinjiang !

2024-05-31 03:15 UTC, Justineo requested changes

2024-05-31 03:15 UTC, Justineo commented on packages/docs/.vitepress/config/zh.ts
> +              text: '活跃的链接',
我们之前翻译 [activeClass](https://router.vuejs.org/zh/api/interfaces/RouterLinkProps.html#Properties-activeClass) 应该用的是“匹配”？

2024-05-31 03:15 UTC, Justineo commented on packages/docs/zh/guide/advanced/composition-api.md
> +navigate
这里都缺缩进是原文也有问题吗

2024-05-31 03:15 UTC, Justineo commented on packages/docs/zh/guide/advanced/data-fetching.md
> +    // 监听路由的参数，以便再次获取数据
根据[翻译约定](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)，watch/observe 都是“侦听”。

2024-05-31 03:15 UTC, Justineo commented on packages/docs/zh/guide/advanced/navigation-guards.md
> +当配合[嵌套路由](../essentials/nested-routes)使用时，父路由和子路由都可以使用 `beforeEnter`。如果放在父级路由上，路径在具有相同父级的子路由之间移动时不会被触发。例如：
这里和下面的 route 要翻译成“路径”吗？

2024-05-31 03:15 UTC, Justineo commented on packages/docs/zh/guide/advanced/navigation-guards.md
> +你也可以通过使用[路径 meta 字段](./meta.md)和全局导航守卫来实现类似的行为。
route meta fields 是不是应该要翻译成“路由元信息字段”？

2024-05-31 03:15 UTC, Justineo commented on packages/docs/zh/guide/essentials/named-routes.md
> +- 没有硬编码的 URL
```suggestion
- 没有硬编码的 URL。
```

2024-05-31 03:15 UTC, Justineo commented on packages/docs/zh/guide/essentials/named-routes.md
> +- 防止你在 url 中出现打字错误。
```suggestion
- 防止你在 URL 中出现打字错误。
```

另外这里原文是 typo 的话用拼写错误是不是更好一点

2024-06-02 22:13 UTC, Jinjiang commented on packages/docs/zh/guide/advanced/navigation-guards.md
> +你也可以通过使用[路径 meta 字段](./meta.md)和全局导航守卫来实现类似的行为。
嗯，我觉得可以翻译成“元信息”

2024-06-02 22:56 UTC, Jinjiang commented on packages/docs/zh/guide/advanced/navigation-guards.md
> +当配合[嵌套路由](../essentials/nested-routes)使用时，父路由和子路由都可以使用 `beforeEnter`。如果放在父级路由上，路径在具有相同父级的子路由之间移动时不会被触发。例如：
route 应该还是翻译成“路由”，我改一下

2024-06-02 23:02 UTC, Jinjiang commented
@Justineo 已全部更新，麻烦再看一下🙏

2024-06-11 03:20 UTC, merged